Update pkginfo
This fixes a regression where an exception is raised when setting up
OpenTitan's Python dependencies:

.../.cache/bazel/.../.../external/rules_python/python/pip_install/extract_wheels/lib/wheel.py", line 57, in entry_points
    name = "{}-{}".format(metadata.name.replace("-", "_"), metadata.version)
AttributeError: 'NoneType' object has no attribute 'replace'

The issue seems related to the previous version of pkginfo not being able to
parse newer versions of Python package metadata, although the reason why this
started failing all of a sudden has not been root caused.

Signed-off-by: Noah Moroze <noah@opentitan.org>